# kubernetes.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: crud-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: crud-api
  template:
    metadata:
      labels:
        app: crud-api
    spec:
      containers:
        - name: crud-api
          image: fais786/crudapitest:latest
          resources:
            limits:
              memory: "256Mi"
              cpu: "0.5m"
          ports:
            - containerPort: 5000

---
apiVersion: v1
kind: Service
metadata:
  name: crud-api
spec:
  selector:
    app: crud-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LaodBalancer
